location: src
sources:
  - repo: git@github.com:SkyRats/PX4-Autopilot.git
    name: PX4-Autopilot
    rev: master
    type: git
    scripts:
      - git submodule update --init --recursive --force
  - repo: git@github.com:mavlink/mavros.git
    name: mavros
    rev: 1.4.0
    type: git
    
default_group: ''
groups:
  -
