location: src/
sources:
  - repo: https://github.com/SkyRats/PX4-Autopilot
    name: PX4-Autopilot
    rev: master
    type: git
    scripts:
      - git submodule update --init --recursive --force
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
  - repo: https://github.com/eProsima/foonathan_memory_vendor.git
    name: foonathan_memory_vendor
    rev: master
    type: git
  - repo: https://github.com/eProsima/Fast-DDS-Gen.git
    name: Fast-DDS-Gen
    rev: v1.0.4
    type: git
  - repo: https://github.com/PX4/px4_ros_com.git 
    name: px4_ros_com
    rev: master
    type: git
  - repo: https://github.com/PX4/px4_msgs.git 
    name: px4_msgs
    rev: master
    type: git

default_group: ''
groups:
  -
