location: .gitman
sources:
  - repo: git@github.com:SkyRats/PX4-Autopilot.git
    name: PX4-Autopilot
    rev: master
    type: git
    scripts:
      - git submodule update --init --recursive --force
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/PX4-Autopilot
  - repo: git@github.com:mavlink/mavros.git
    name: mavros
    rev: 1.4.0
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
default_group: ''
groups:
  -
