location: .gitman
sources:
  - repo: git@github.com:PX4/PX4-Autopilot.git
    name: px4_firmware
    rev: ecc2ca7f9829cc0ca70fae7583877d8a62c06d3e
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 
  - repo: git@github.com:mavlink/mavlink.git
    name: mavlink
    rev: 5309ba449a3dc6d7ad84fa7ebeb6deee040e4a04
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavlink
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mavlink/mavros.git
    name: mavros
    rev: c6c609a2642a6bf875c96987e6856607345fea3f
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
