location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.11.2
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
  - repo: git@github.com:mavlink/mavros.git
    name: mavros
    rev: 1.4.0
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
default_group: ''
groups:
  -
